import { GoogleGenAI, mcpToTool } from '@google/genai';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { SSEClientTransport } from '@modelcontextprotocol/sdk/client/sse.js';
import crypto from 'crypto';

// Helper function to generate a JWT and swap it for a user-scoped Salesforce Access Token
async function getSalesforceUserToken() {
  const consumerKey = process.env.SF_CONSUMER_KEY;
  const username = 'rajrao104-3972@dev.org'; 
  const audience = 'https://login.salesforce.com';
  
  const header = Buffer.from(JSON.stringify({ alg: 'RS256', typ: 'JWT' })).toString('base64url');
  const claimSet = Buffer.from(JSON.stringify({
    iss: consumerKey,
    sub: username,
    aud: audience,
    exp: Math.floor(Date.now() / 1000) + 180 
  })).toString('base64url');

  const signInput = `${header}.${claimSet}`;
  const privateKey = process.env.SF_PRIVATE_KEY.replace(/\\n/g, '\n'); 
  const signer = crypto.createSign('RSA-SHA256');
  signer.update(signInput);
  const signature = signer.sign(privateKey, 'base64url');

  const assertionToken = `${signInput}.${signature}`;

  const params = new URLSearchParams({
    grant_type: 'urn:ietf:params:oauth:grant-type:jwt-bearer',
    assertion: assertionToken
  });

  const response = await fetch(`https://${process.env.SF_DOMAIN}.my.salesforce.com/services/oauth2/token`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: params
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Salesforce JWT Handshake Failure: ${errorText}`);
  }

  const tokenData = await response.json();
  return tokenData.access_token;
}

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'HTTP Method unsupported' });
  }

  // Define transport outside the scope so we can cleanly disconnect later
  let transport = null;

  try {
    // 1. Fetch our user-specific Salesforce authorization token
    const sfAccessToken = await getSalesforceUserToken();

    // 2. Initialize the standard Model Context Protocol SDK Client Transport
    // This establishes the authenticated handshake straight to your Salesforce SSE Gateway endpoint
    transport = new SSEClientTransport(new URL(process.env.SALESFORCE_MCP_URL), {
      requestInit: {
        headers: {
          'Authorization': `Bearer ${sfAccessToken}`,
          'Content-Type': 'application/json'
        }
      }
    });

    const mcpClient = new Client({
      name: "vercel-mcp-client-bridge",
      version: "1.0.0"
    }, { capabilities: {} });

    // Connect to the active Salesforce MCP instance
    await mcpClient.connect(transport);

    // 3. CONVERT THE CLIENT TO A GEMINI READABLE TOOL
    // This reads the dynamic metadata generated by your global Invocable Variables schema
    const salesforceGeminiTool = await mcpToTool(mcpClient);

    const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

    // 4. Run your prompt execution sweep
    const aiResponse = await ai.models.generateContent({
      model: 'gemini-2.5-flash', 
      contents: req.body.message,
      config: {
        systemInstruction: `You are an operational flight reservation coordinator agent. 
        You have absolute access to the user's secure CRM data through the connected Salesforce Invocable Actions MCP Server.
        
        CRITICAL DATE PARSING INSTRUCTIONS:
        When processing human date requests, extract the specific intent and strictly pass it into the 'dateFilter' variable as one of these alphanumeric keywords:
        - "Flights today" -> TODAY
        - "Trips next month" -> NEXT_MONTH
        - "This upcoming weekend" -> WEEKEND
        
        Always translate raw record structures (Name, Price__c, FlightId__c) back into conversational, friendly summaries for the webpage UI layout. Do not stop at explaining what you are searching; retrieve the data using your tools and present the final list.`,
        
        // Feed the structural callable tool representation into the execution context
        tools: [salesforceGeminiTool]
      }
    });

    // Clean disconnect to free serverless framework overhead 
    await mcpClient.close();

    // Verify structural object properties match front end assumptions
    if (aiResponse && aiResponse.text) {
        return res.status(200).json({ reply: aiResponse.text });
    } else {
        return res.status(200).json({ reply: "Search processed cleanly, but no record array matching that window description exists inside your CRM profile." });
    }

  } catch (error) {
    console.error("Execution Crash Log: ", error.message);
    return res.status(500).json({ error: `Serverless Error: ${error.message}` });
  }
}